# Generated by Django 3.2.9 on 2021-11-30 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_person_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='message',
        ),
    ]
