# Generated by Django 3.2.9 on 2021-11-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_remove_person_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='message',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
